@testable import AreaMatrix

typealias SmokeStaticSettingsReader = StaticSettingsReader

typealias SmokeRecordingSettingsWriter = RecordingAppSettingsWriter

typealias SmokeRecordingConfigLoader = RecordingConfigurationLoader

typealias SmokeRecordingPathValidator = RecordingRepositoryPathValidator

typealias SmokeRecordingRepositoryOpener = RecordingRepositoryOpener

typealias SmokeRecordingScanSessionReader = RecordingScanSessionReader

typealias SmokeNoopWelcomeHelpOpener = NoopWelcomeHelpOpener

typealias SmokeExistingRepoMetadataReader = StaticExistingRepositoryMetadataReader
