let featureLocalDoubleDeclarations = [
    "struct DatabaseRepairMetadataRepairRequest", "actor DatabaseRepairRecordingMetadataRepairer",
    "enum ChangeCategoryRequest", "actor ChangeCategoryRecordingMover",
    "typealias ChangeCategoryRecordingPredictor", "typealias ChangeCategoryRecordingLister",
    "enum DeleteRequest", "actor DeleteRecordingDeleter",
    "final class RecordingExternalURLPlatformOpener", "final class RecordingExternalURLStringOpener",
    "final class RecordingLocalFileURLResourceReader", "final class RecordingLocalFileURLPlatformOpener",
    "final class RecordingLocalFileURLOpener",
    "typealias DetailLogRecordingLister", "struct RenameRequest",
    "actor RenameRecordingRenamer", "struct BatchRenamePreviewRequest",
    "struct BatchRenameApplyRequest", "actor BatchRenameRecordingRenamer",
    "struct ImportBatchBatchImportRequest", "actor ImportBatchRecordingBatchImporter",
    "actor ImportBatchSequenceBatchImporter", "actor ImportBatchStaticBatchFileLoader",
    "struct ImportBatchNameConflictPrecheckRequest", "actor ImportBatchStaticNameConflictPrechecker",
    "struct ImportSingleFileStaticLocalizedError", "struct ImportSingleFileImportRequest",
    "struct ImportSingleFileCoreImportRequest", "typealias ImportSingleFileStaticICloudDownloader",
    "typealias ImportSingleFilePredictRequest", "typealias ImportSingleFileRecordingPredictor",
    "typealias ImportSingleFileStaticRepositoryOpener", "struct ImportSingleFileStaticPreflight",
    "struct ImportSingleFileFileLoadRequest", "actor ImportSingleFileStaticFileLoader",
    "actor ImportSingleFileRecordingImporter", "actor ImportSingleFileSuspendingImporter",
    "actor ImportSingleFileImportGate", "actor ImportSingleFileFailingImporter",
    "typealias ImportFolderPredictRequest",
    "typealias ImportFolderRecordingPredictor",
    "typealias ImportFolderMappedPredictor",
    "typealias ImportFolderRecordingICloudDownloader",
    "struct ImportFolderStaticFolderScanner",
    "actor ImportFolderSequenceFolderScanner",
    "struct ImportFolderConflictPrecheckRequest",
    "actor ImportFolderStaticConflictPrechecker",
    "actor ImportFolderNoopConflictPrechecker",
    "typealias ShellStaticSettingsReader",
    "typealias ShellRecordingSettingsWriter",
    "typealias ShellRecordingConfigLoader",
    "typealias ShellRecordingRepositoryOpener",
    "typealias ShellRecordingPathValidator",
    "typealias ShellRecordingInitializedPathValidator",
    "typealias ShellRecordingExternalChangesSyncer",
    "typealias ShellRecordingDiagnosticsCollector",
    "typealias ShellRecordingRepositoryInitializer",
    "typealias ShellStaticScanSessionReader",
    "typealias ShellStaticImportBatchSessionStore",
    "struct ShellFailingWelcomeHelpOpener",
    "final class ShellRecordingPathCopier",
    "typealias ShellExistingRepoMetadataReader",
    "final class ShellRecordingDirectoryPicker",
    "struct ShellStaticImportPicker",
    "typealias ImportConflictChangeLogRequest",
    "typealias ImportConflictChangeLogLister",
    "struct ImportConflictPreviewRequest",
    "struct ImportConflictApplyRequest",
    "actor ImportConflictBatcher",
    "typealias ImportResultChangeLogRequest",
    "typealias ImportResultRecordingChangeLogLister",
    "final class ImportResultExporter",
    "actor DetailMetaImmediateDetailer",
    "struct FileDetailRequest",
    "actor RecordingFileDetailer",
    "actor RepoSettingsMetadataReader",
    "typealias RepoSettingsRepositoryOpener",
    "typealias RepoSettingsScanSessionReader",
    "final class RecordingRepoMetadataPresenceChecker",
    "typealias RepoSettingsCapabilityLoader",
    "typealias AITagSuggestionAISettingsLoader",
    "typealias SmartListRecordingSmartListRunner",
    "typealias SmokeStaticSettingsReader",
    "typealias SmokeRecordingSettingsWriter",
    "typealias SmokeRecordingConfigLoader",
    "typealias SmokeRecordingPathValidator",
    "typealias SmokeRecordingRepositoryOpener",
    "typealias SmokeRecordingScanSessionReader",
    "typealias SmokeNoopWelcomeHelpOpener",
    "typealias SmokeExistingRepoMetadataReader",
    "typealias ImportDropPredictRequest",
    "typealias ImportDropRecordingPredictor",
    "struct MainEmptyImportStaticImportPicker",
    "actor MainLoadingPausingStartupRecoverer",
    "actor MainLoadingRecordingTreeLister",
    "actor MainLoadingInitializedPathValidator",
    "actor MainLoadingPausingRepositoryOpener",
    "typealias MainLoadingFailingRepositoryOpener",
    "typealias MainLoadingRecordingSettingsWriter",
    "typealias MainListIntegrationDetailer",
    "typealias MainListIntegrationDiagnosticsCollector",
    "typealias MainListIntegrationNoopDetailer",
    "typealias MainListRecordingFileLister",
    "typealias MainListRecordingSearchQuerying",
    "typealias MainListSearchRequestRecord",
    "typealias MainListSmartListRequestRecord",
    "struct MainListFallbackRequestRecord",
    "actor MainListRecordingSemanticSearcher",
    "actor MainListRecordingSemanticFallbackReader",
    "actor MainListIntegrationSuspendedLister",
    "typealias SemanticSearchDetailer",
    "typealias SemanticSearchLister",
    "typealias SemanticSearchNormalSearcher",
    "typealias SemanticSearchPageDetailer",
    "typealias SemanticSearchPageLister",
    "typealias SemanticSearchPageNormalSearcher",
    "actor SemanticSearchSemanticSearcher",
    "actor SemanticSearchPagedSemanticSearcher",
    "actor SemanticSearchDelayedSemanticSearcher",
    "typealias SmartListSmartListRunRequest",
    "typealias SyncConflictReviewRecordingFileDetailer",
    "struct SyncConflictPreviewRequest",
    "struct SyncConflictResolveRequest",
    "typealias ICloudPathValidator"
]

let bridgeBoundaryDeclarations = [
    "actor AIPrivacyRulesFailingBridge",
    "actor FileActionsRecordingCore",
    "actor ICloudConflictMinimalRecordingMainCore",
    "actor ICloudConflictResolver",
    "actor ICloudConflictReviewer",
    "actor RemotePrivacyRulesBridge"
]

let semanticRequestAssertionFileNames = [
    "AICallLogTestDoubleSupport.swift",
    "AICategorySuggestionPageIntegrationVerifyTests.swift",
    "DatabaseRepairConfirmPageTestDoubleSupport.swift",
    "DeleteFilePageTestDoubleSupport.swift",
    "DiagnosticsTestDoubleSupport.swift",
    "ExternalURLPolicyTestDoubleSupport.swift",
    "LocalFileURLOpenerTestDoubleSupport.swift",
    "PlatformIntrospectionTestDoubleSupport.swift",
    "RepositoryFileActionTestDoubleSupport.swift",
    "RepositoryOpeningTestDoubleSupport.swift",
    "RepositorySettingsTestDoubleSupport.swift",
    "StartupRecoveryTestDoubleSupport.swift",
    "AreaMatrixShellTestDoubleSupport.swift",
    "AICategorySuggestionBridgeTestSupport.swift",
    "AISettingsTestDoubleSupport.swift",
    "AITagSuggestionBridgeTestSupport.swift",
    "ConfigurationTestDoubleSupport.swift",
    "RemoteProviderConfigBridgeTestSupport.swift",
    "RemotePrivacyRulesBridgeTestSupport.swift",
    "SearchFiltersTestDoubleSupport.swift",
    "SearchQueryTestDoubleSupport.swift",
    "DetailTagTestDoubleSupport.swift",
    "RenameFilePageTestDoubleSupport.swift",
    "ClassifierSettingsBridgeTestSupport.swift",
    "UndoRedoActionSnapshotTestDoubleSupport.swift",
    "BatchAddTagsTestDoubleSupport.swift",
    "ImportConflictIntegrationTestDoubleSupport.swift",
    "NoteTestDoubleSupport.swift"
]

let genericRequestAssertionTerms = [
    "Requests",
    "NoRequests",
    "FirstRequest",
    "LastRequest",
    "SingleRequest",
    "AddRequests",
    "RemoveRequests",
    "ListRequests",
    "ListRequestFileIDs",
    "PreviewRequests",
    "ApplyRequests",
    "UndoRequests",
    "RedoRequests",
    "NoDeleteRequests",
    "ReadRequests",
    "WriteRequests",
    "NoWriteRequests",
    "SingleCreateRequest",
    "SingleUpdateRequest",
    "SingleDeleteRequest",
    "SuggestionRequests",
    "ApplySuggestionRequests",
    "NoApplySuggestionRequests",
    "LastApplySuggestionRequestSuggestions"
].map { "func assert\($0)(" }

let rawRecordExposureTerms = [
    "func recordedRequests()", "func recordedActionCalls()", "func recordedURLs()", "func requestedRepoPaths()",
    "func requestedPaths()", "func recordedRepoPaths()", "func recordedResumeRequests()",
    "func createRequests()", "func updateRequests()", "func deleteRequests()", "func previewRequests()",
    "func applyRequests()", "func listRequests()", "func undoRequests()", "func redoRequests()",
    "func statusRequests()", "func folderRequests()", "func loadRequests()", "func batchRequests()",
    "func savedSessions()", "func clearedRepoPaths()", "func requestCount()",
    "func observedCancellationCount()", "func routes()", "private(set) var requests",
    "private(set) var repoPaths", "private(set) var multiPathRequests",
    "private(set) var openedPaths", "private(set) var createdPaths", "private(set) var openedLinks",
    "private(set) var openedRepoPaths", "private(set) var paths", "private(set) var values",
    "private(set) var copiedSummaries", "private(set) var chooseCount", "private(set) var openCount",
    "private(set) var requestCount", "private(set) var summaries", "private(set) var locations",
    "private(set) var requestedURLs", "private(set) var openedURLs", "private(set) var revealedURLs",
    "private(set) var openURLs", "private(set) var openExistingRequests",
    "private(set) var revealExistingURLs", "private(set) var openedValues",
    "private(set) var savedRepoPaths", "private(set) var successfulRepoOpens",
    "private(set) var announcements", "var messages: [String]", "var successfulRepoOpenPaths: [String]",
    "protocol RecordedRequestRecording", "recordedRequestsForAssertions", "func assertRecordedRequests(",
    "func assertNoRecordedRequests(", "func assertRecordedRequestCount(", "func assertLastRecordedRequest(",
    "func assertRecordedFilters(", "func assertRecordedRequestFilenames(", "func assertRecordedActionCalls(",
    "func assertRecordedSemanticFallbackRequests(", "func assertRecordedPreviewResolutions(", "RecordedResume",
    "func assertRecordedResolveRequestCount(", "func assertRecordedPreviewRequests(", "RecordedPrecheck",
    "func assertRecordedResolveRequests(", "func assertRecordedCreateRequests(", "func assertRecordedQueries(",
    "func assertRecordedUpdateRequests(", "func assertRecordedDeleteRequests(", "RecordedOutOfScopeActions",
    "func assertRecordedListRepoPaths(", "func assertRecordedCoreRequests(", "RecordedKeepBothRequest",
    "func assertRecordedConfigCount(", "func assertRecordedConfigValues(", "func assertRecordedConfigValue(",
    "func assertRecordedErrors(", "func assertRecordedErrorCount(", "func assertPreviewRequestCount(",
    "func assertFirstRecordedInternalErrorContains(", "func assertLastApplyRequest(",
    "func assertPreviewStrategies(", "func assertPreviewScopes(", "func assertNoApplyRequests(",
    "func assertPreviewRequests(", "func assertApplyRequests("
]

let rawRecordLocalFileNames = [
    "ICloudConflictListPageFeatureTests.swift",
    "MainEmptyBuildTreeTests.swift"
]

let inlineTestDoubleNameMarkers = [
    "Recording", "Recorder", "Noop", "TestDouble", "Stub", "Spy"
]

let inlineTestDoubleInventory: [String] = []
