import AreaMatrixPlatformKit

typealias LocalFileURLResourceSnapshot = AreaMatrixPlatformKit.LocalFileURLResourceSnapshot
typealias LocalFileURLOpenError = AreaMatrixPlatformKit.LocalFileURLOpenError
typealias LocalFileURLResourceReading = AreaMatrixPlatformKit.LocalFileURLResourceReading
typealias LocalFileURLPlatformOpening = AreaMatrixPlatformKit.LocalFileURLPlatformOpening
typealias LocalFileURLOpening = AreaMatrixPlatformKit.LocalFileURLOpening
typealias FileManagerLocalFileURLResourceReader = AreaMatrixPlatformKit.FileManagerLocalFileURLResourceReader
typealias NSWorkspaceLocalFileURLPlatformOpener = AreaMatrixPlatformKit.NSWorkspaceLocalFileURLPlatformOpener
typealias NSWorkspaceLocalFileURLOpener = AreaMatrixPlatformKit.NSWorkspaceLocalFileURLOpener
