--swiftversion 5.9
--exclude AreaMatrix/Bridge/Generated,AreaMatrix/Bridge/UniFFI
--indent 4
--maxwidth 120
--trailing-commas never
--trim-whitespace always
--ifdef no-indent
--self remove
--header strip
--disable wrapMultilineStatementBraces
