import AreaMatrixUIFoundation

typealias AreaMatrixColorToken = AreaMatrixUIFoundation.AreaMatrixColorToken
typealias AreaMatrixParallax = AreaMatrixUIFoundation.AreaMatrixParallax
typealias AreaMatrixAmbientScene = AreaMatrixUIFoundation.AreaMatrixAmbientScene
typealias AreaMatrixTheme = AreaMatrixUIFoundation.AreaMatrixTheme
