import AreaMatrixPlatformKit

typealias ExternalURLPolicy = AreaMatrixPlatformKit.ExternalURLPolicy
typealias ExternalURLOpenError = AreaMatrixPlatformKit.ExternalURLOpenError
typealias ExternalURLStringOpening = AreaMatrixPlatformKit.ExternalURLStringOpening
typealias ExternalURLPlatformOpening = AreaMatrixPlatformKit.ExternalURLPlatformOpening
typealias NSWorkspaceExternalURLPlatformOpener = AreaMatrixPlatformKit.NSWorkspaceExternalURLPlatformOpener
typealias NSWorkspaceExternalURLStringOpener = AreaMatrixPlatformKit.NSWorkspaceExternalURLStringOpener
